# Generated by Django 6.0.1 on 2026-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
