# Generated by Django 6.0.1 on 2026-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
