# Generated by Django 6.0.1 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonapp', '0003_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
